version: '3.9'
services:
  dev-web:
    image: web-image-name
    container_name: web-container-name
    restart: always
    networks:
      - liboboa
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILE: prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - logs:/javarun/logs
      - data:/data
    ports:
      - "8080:8080"
volumes:
  logs:
  data:
networks:
  liboboa:
    name: liboboa
    external: true
