version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - liboboa
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
#   sql_mode 去除 only_full_group_by
    command: ["mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--lower_case_table_names=1"]
networks:
  liboboa:
    name: liboboa
    external: true
volumes:
  data:
