version: "3"

services:
  server:
    image: mysql
    container_name: mysql8
    volumes:
      - /data/mysql8-2/config:/etc/mysql
      - /data/mysql8-2/config/my.cnf:/etc/mysql/my.cnf
      - /data/mysql8-2/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
