# 暂不可用
version: "3"
services:
  server:
    image: nginx
    container_name: nginx
    volumes:
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/logs:/var/log/nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
