version: '3.8'
services:
  logserver:
    image: codeskyblue/gohttpserver
    container_name: logserver
    restart: always
    networks:
      - liboboa
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ruoyi-admin_logs:/app/public
    command: ["--auth-type", "http", "--auth-http", "username:password"]
networks:
  liboboa:
    name: liboboa
volumes:
  web_logs:
    external: true
