version: '3'
services:
  redis:
    image: redis
    container_name: compose_redis
    volumes:
      - /data/redis-compose/data:/data
      - /data/redis-compose/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis-compose/logs:/logs
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
